### ISSUE TITLE
Add setup instructions for how to run the example applications

### ISSUE THREAD

**Issue by foxish** [signadot/examples#4]
This will include:

1. Spinning up some local cluster (minikube etc) - this can just be a link out to relevant docs
2. Deploying hotrod - using https://github.com/signadot/hotrod/blob/main/k8s/all-in-one/demo.yaml
3. Connecting cluster to signadot - simple description
4. Using a set of images we have already published to spin up new workspaces (show 2-3 different image tags that we have named appropriately - like `signadot/hotrod-route:bugfix-slow-cars` or `signadot/hotrod-frontend:improve-ui`
 
The goal here is to ensure that someone can come into the application and set up and run these examples to get an understanding of workspaces without having to compile code or build new images.

cc @jmsktm @arjun-sd

**Comment by jmsktm** [comment]
@foxish: Wdyt about building a Docker image with all the setup baked in, thereby allowing the user to perform the setup by literally running a single `docker-run ...` command?
